name = "menu"
compatibility_date = "2023-01-01"
workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[[kv_namespaces]]
binding = "MENU"
id = "a63f1fb0b3f3478e9e3c99601546d3b4"
preview_id = "a63f1fb0b3f3478e9e3c99601546d3b4"
